import { useCallback, useEffect, useMemo, useState } from 'react'
import type { ProviderId, SkillEntry, SkillFileNode } from '@shared/types'
import { api } from '@/platform/api'
import { MindexGlyph } from '@/ui/mindex-glyph'
import { ProviderGlyph } from '@/ui/provider-glyph'
import { EmptyState } from '@/ui/EmptyState'
import { ConfirmDialog } from '@/ui/ConfirmDialog'
import { promptText } from '@/ui/prompt'
import { onSkillsChanged, requestCreateSkill } from '@/features/skills/lib/create'
import { noteLook } from '@/platform/presentation'
import { SidebarChildren, SidebarRow } from './SidebarRow'
import { SidebarContextMenu, type SidebarMenuItem } from './SidebarContextMenu'
import { openDocument, skillViewPath, useActiveDocumentPath } from '@/platform/documents'

interface SkillGroup {
  name: string
  description?: string
  providers: ProviderId[]
  /** Absolute path to the skill folder — what its files are resolved against. */
  path: string
  files: SkillFileNode[]
  /** Written by Mindex: shown with a neutral mark, and not the user's to rename. */
  generated: boolean
}

// Scans return one raw row per (provider, scope, name) — merge rows that
// share a name within the same scope into a single listing, collecting
// every provider that has a skill by that name so the row can tell "yours
// alone" from "shared" apart (the Mindex mark vs a specific provider's).
function groupByScope(entries: SkillEntry[]): Record<'project' | 'global', SkillGroup[]> {
  const maps: Record<'project' | 'global', Map<string, SkillGroup>> = {
    project: new Map(),
    global: new Map()
  }
  for (const e of entries) {
    const map = maps[e.scope]
    const existing = map.get(e.name)
    if (existing) {
      if (!existing.providers.includes(e.provider)) existing.providers.push(e.provider)
      if (!existing.description && e.description) existing.description = e.description
      if (e.generated) existing.generated = true
      // Keep the path of whichever copy actually has files, so the rows
      // below resolve against the folder they came from.
      if (existing.files.length === 0 && e.files.length > 0) {
        existing.files = e.files
        existing.path = e.path
      }
    } else {
      map.set(e.name, {
        name: e.name,
        description: e.description,
        providers: [e.provider],
        path: e.path,
        files: e.files,
        generated: e.generated === true
      })
    }
  }
  const byName = (a: SkillGroup, b: SkillGroup): number => a.name.localeCompare(b.name)
  return {
    project: [...maps.project.values()].sort(byName),
    global: [...maps.global.values()].sort(byName)
  }
}

type Menu = { x: number; y: number; items: SidebarMenuItem[] }

/**
 * Skills read straight off disk — Claude/Codex/Gemini's own
 * `~/.<provider>/skills/<name>/SKILL.md` folders (global) and the matching
 * folder at the vault root (project).
 *
 * The mark on the right says whose the skill is: a specific provider's badge
 * when it lives in only that provider's folder, and the Mindex mark when it
 * either spans several or was generated by Mindex — in both of those cases the
 * skill is about the vault, not about which CLI happens to read it.
 */
export function SkillsPane(): JSX.Element {
  // A new tab, not a replacement: picking a file in the sidebar is adding
  // something to look at, and it should not close what you were already
  // looking at. Already-open paths are focused rather than duplicated.
  const openTab = openDocument
  const activePath = useActiveDocumentPath()
  const [entries, setEntries] = useState<SkillEntry[]>([])
  const [loading, setLoading] = useState(true)
  const [expanded, setExpanded] = useState<Set<string>>(new Set())
  const [menu, setMenu] = useState<Menu | null>(null)
  const [confirming, setConfirming] = useState<{ path: string; label: string } | null>(null)

  const refresh = useCallback(async (): Promise<void> => {
    // Preload-bridge changes need a full Electron restart, not just a
    // renderer reload — guard the call itself so a stale bridge (mid dev
    // session, before that restart) shows an empty list instead of crashing
    // the tree.
    const bridge = api().skills
    if (!bridge?.list) {
      setEntries([])
      setLoading(false)
      return
    }
    const r = await bridge.list()
    setEntries(r.ok && r.data ? r.data : [])
    setLoading(false)
  }, [])

  useEffect(() => {
    void refresh()
    return onSkillsChanged(() => void refresh())
  }, [refresh])

  const grouped = useMemo(() => groupByScope(entries), [entries])

  function toggle(key: string): void {
    setExpanded((prev) => {
      const next = new Set(prev)
      if (next.has(key)) next.delete(key)
      else next.add(key)
      return next
    })
  }

  async function rename(absPath: string, current: string): Promise<void> {
    const next = await promptText({
      title: 'Rename',
      message: 'The folder or file is renamed on disk.',
      initialValue: current,
      confirmLabel: 'Rename'
    })
    if (!next || next === current) return
    await api().skills.rename(absPath, next)
    await refresh()
  }

  async function addEntry(parentDir: string, kind: 'file' | 'folder'): Promise<void> {
    const name = await promptText({
      title: kind === 'file' ? 'New file' : 'New folder',
      placeholder: kind === 'file' ? 'reference.md' : 'scripts',
      confirmLabel: 'Create'
    })
    if (!name) return
    const r = await api().skills.createEntry(parentDir, name, kind)
    await refresh()
    if (kind === 'file' && r.ok && r.data) {
      setExpanded((prev) => new Set(prev).add(parentDir))
      void openTab(skillViewPath(r.data.path))
    }
  }

  function skillMenu(skill: SkillGroup): SidebarMenuItem[] {
    const items: SidebarMenuItem[] = [
      { label: 'New skill', onClick: () => void requestCreateSkill() },
      { label: 'New file', icon: 'new-file', onClick: () => void addEntry(skill.path, 'file') },
      {
        label: 'New folder',
        icon: 'new-folder',
        onClick: () => void addEntry(skill.path, 'folder')
      },
      {
        label: 'Reveal in Finder',
        icon: 'folder-opened',
        onClick: () => void api().skills.reveal(skill.path)
      }
    ]
    // A generated skill is rewritten from the vault's types, so renaming its
    // folder would simply be undone on the next sync.
    if (!skill.generated) {
      items.splice(2, 0, {
        label: 'Rename',
        icon: 'edit',
        onClick: () => void rename(skill.path, skill.path.split('/').pop() ?? skill.name)
      })
    }
    items.push({
      label: 'Delete skill',
      icon: 'trash',
      destructive: true,
      separatorBefore: true,
      onClick: () => setConfirming({ path: skill.path, label: skill.name })
    })
    return items
  }

  function fileMenu(node: SkillFileNode): SidebarMenuItem[] {
    const items: SidebarMenuItem[] = []
    if (node.isDir) {
      items.push(
        { label: 'New file', icon: 'new-file', onClick: () => void addEntry(node.path, 'file') },
        {
          label: 'New folder',
          icon: 'new-folder',
          onClick: () => void addEntry(node.path, 'folder')
        }
      )
    }
    items.push(
      { label: 'Rename', icon: 'edit', onClick: () => void rename(node.path, node.name) },
      {
        label: 'Reveal in Finder',
        icon: 'folder-opened',
        onClick: () => void api().skills.reveal(node.path)
      },
      {
        label: node.isDir ? 'Delete folder' : 'Delete file',
        icon: 'trash',
        destructive: true,
        separatorBefore: true,
        onClick: () => setConfirming({ path: node.path, label: node.name })
      }
    )
    return items
  }

  /** One level of the folder, recursing into whatever it contains. */
  function renderNodes(nodes: SkillFileNode[]): JSX.Element {
    return (
      <SidebarChildren>
        {nodes.map((node) => {
          const icon = node.isDir
            ? { name: expanded.has(node.path) ? 'folder-opened' : 'folder', color: null }
            : // Was the extension default alone, which ignored a chosen icon.
              (() => {
                const look = noteLook(node.path, node.name)
                return { name: look.icon ?? 'file', color: look.colorClass }
              })()
          const open = expanded.has(node.path)
          return (
            <div key={node.path}>
              <SidebarRow
                label={node.name}
                icon={icon.name}
                iconClassName={icon.color ?? 'text-muted-foreground'}
                active={activePath === skillViewPath(node.path)}
                title={node.path}
                {...(node.isDir
                  ? { expandable: true, expanded: open, onClick: () => toggle(node.path) }
                  : { onClick: () => void openTab(skillViewPath(node.path)) })}
                onContextMenu={(e) => {
                  e.preventDefault()
                  setMenu({ x: e.clientX, y: e.clientY, items: fileMenu(node) })
                }}
              />
              {node.isDir && open
                ? node.children && node.children.length > 0
                  ? renderNodes(node.children)
                  : emptyRow()
                : null}
            </div>
          )
        })}
      </SidebarChildren>
    )
  }

  if (loading) return <div className="flex-1 overflow-auto px-1" />

  const sections: { key: 'project' | 'global'; label: string; items: SkillGroup[] }[] = [
    { key: 'project', label: 'Project', items: grouped.project },
    { key: 'global', label: 'Global', items: grouped.global }
  ]

  if (sections.every((s) => s.items.length === 0)) {
    return (
      <div className="tree-scroll flex-1 overflow-auto px-1">
        <EmptyState
          icon="sparkle"
          title="No skills found."
          hint="Skills live in ~/.claude/skills, ~/.codex/skills or ~/.gemini/skills — or the matching folder at your vault root."
          action={{
            label: 'New skill',
            icon: 'empty-window',
            onClick: () => void requestCreateSkill()
          }}
        />
      </div>
    )
  }

  return (
    <div
      className="tree-scroll flex-1 overflow-auto px-1"
      // Right-clicking the empty part of the pane is how you create the first
      // thing in it — with no rows yet there is nothing else to aim at.
      onContextMenu={(e) => {
        if (e.defaultPrevented) return
        e.preventDefault()
        setMenu({
          x: e.clientX,
          y: e.clientY,
          items: [{ label: 'New skill', onClick: () => void requestCreateSkill() }]
        })
      }}
    >
      {sections.map((section) =>
        section.items.length > 0 ? (
          <div key={section.key} className="mb-1">
            <div className="px-2 pb-1 pt-2 text-[11px] font-medium uppercase tracking-wide text-muted-foreground/70">
              {section.label}
            </div>
            {section.items.map((skill) => {
              const key = `${section.key}:${skill.name}`
              const open = expanded.has(key)
              const soleProvider = skill.providers[0]
              const neutral = skill.generated || skill.providers.length > 1 || !soleProvider
              return (
                <div key={key}>
                  <SidebarRow
                    label={skill.name}
                    expandable
                    expanded={open}
                    title={skill.description}
                    onClick={() => toggle(key)}
                    onContextMenu={(e) => {
                      e.preventDefault()
                      setMenu({ x: e.clientX, y: e.clientY, items: skillMenu(skill) })
                    }}
                    trailing={
                      <span className="mr-0.5 flex items-center">
                        {neutral ? (
                          <MindexGlyph size={13} className="text-foreground" />
                        ) : (
                          <ProviderGlyph id={soleProvider} size={13} />
                        )}
                      </span>
                    }
                  />
                  {open ? (skill.files.length > 0 ? renderNodes(skill.files) : emptyRow()) : null}
                </div>
              )
            })}
          </div>
        ) : null
      )}

      {menu ? (
        <SidebarContextMenu state={menu} items={menu.items} onClose={() => setMenu(null)} />
      ) : null}

      <ConfirmDialog
        open={confirming !== null}
        title="Delete from disk?"
        message={
          <>
            <span className="font-medium text-foreground">{confirming?.label}</span> will be removed
            from your filesystem. This cannot be undone.
          </>
        }
        confirmLabel="Delete"
        confirmIcon="trash"
        destructive
        onCancel={() => setConfirming(null)}
        onConfirm={() => {
          const target = confirming?.path
          setConfirming(null)
          if (!target) return
          void api()
            .skills.delete(target)
            .then(() => refresh())
        }}
      />
    </div>
  )
}

function emptyRow(): JSX.Element {
  return (
    <SidebarChildren>
      <div className="px-3 py-1 text-[11px] text-muted-foreground/60">Empty</div>
    </SidebarChildren>
  )
}
