/**
 * A curated subset of common emoji for the block-picker's Emoji entry —
 * not the full Unicode set (~3800 entries), which would need a real dataset
 * dependency. Picking one inserts the literal character as plain text, so
 * there is no markdown-parsing surface to keep in sync as this list grows.
 */
export interface EmojiEntry {
  char: string
  name: string
  keywords: string
}

export const EMOJI_LIST: EmojiEntry[] = [
  { char: '😀', name: 'grinning face', keywords: 'smile happy' },
  { char: '😄', name: 'grinning face with smiling eyes', keywords: 'smile happy laugh' },
  { char: '😂', name: 'face with tears of joy', keywords: 'laugh lol funny' },
  { char: '🙂', name: 'slightly smiling face', keywords: 'smile' },
  { char: '😉', name: 'winking face', keywords: 'wink' },
  { char: '😅', name: 'grinning face with sweat', keywords: 'relief phew' },
  { char: '😊', name: 'smiling face with smiling eyes', keywords: 'blush happy' },
  { char: '😍', name: 'smiling face with heart-eyes', keywords: 'love crush' },
  { char: '🤔', name: 'thinking face', keywords: 'think hmm' },
  { char: '😎', name: 'smiling face with sunglasses', keywords: 'cool' },
  { char: '😴', name: 'sleeping face', keywords: 'sleep tired zzz' },
  { char: '😢', name: 'crying face', keywords: 'sad cry' },
  { char: '😭', name: 'loudly crying face', keywords: 'sad cry sob' },
  { char: '😡', name: 'pouting face', keywords: 'angry mad' },
  { char: '😱', name: 'face screaming in fear', keywords: 'scared shock' },
  { char: '🥳', name: 'partying face', keywords: 'party celebrate' },
  { char: '🤯', name: 'exploding head', keywords: 'mind blown shock' },
  { char: '🙄', name: 'face with rolling eyes', keywords: 'eyeroll' },
  { char: '😇', name: 'smiling face with halo', keywords: 'angel innocent' },
  { char: '🤗', name: 'hugging face', keywords: 'hug' },
  { char: '👍', name: 'thumbs up', keywords: 'approve good yes' },
  { char: '👎', name: 'thumbs down', keywords: 'disapprove bad no' },
  { char: '👏', name: 'clapping hands', keywords: 'applause clap' },
  { char: '🙌', name: 'raising hands', keywords: 'celebrate praise' },
  { char: '🙏', name: 'folded hands', keywords: 'please thanks pray' },
  { char: '👋', name: 'waving hand', keywords: 'wave hello bye' },
  { char: '✋', name: 'raised hand', keywords: 'stop high five' },
  { char: '👌', name: 'ok hand', keywords: 'okay perfect' },
  { char: '✌️', name: 'victory hand', keywords: 'peace' },
  { char: '💪', name: 'flexed biceps', keywords: 'strong muscle' },
  { char: '🤝', name: 'handshake', keywords: 'deal agreement' },
  { char: '❤️', name: 'red heart', keywords: 'love heart' },
  { char: '🧡', name: 'orange heart', keywords: 'love heart' },
  { char: '💛', name: 'yellow heart', keywords: 'love heart' },
  { char: '💚', name: 'green heart', keywords: 'love heart' },
  { char: '💙', name: 'blue heart', keywords: 'love heart' },
  { char: '💜', name: 'purple heart', keywords: 'love heart' },
  { char: '🖤', name: 'black heart', keywords: 'love heart' },
  { char: '🔥', name: 'fire', keywords: 'hot lit flame' },
  { char: '✨', name: 'sparkles', keywords: 'shiny magic new' },
  { char: '⭐', name: 'star', keywords: 'favorite' },
  { char: '🌟', name: 'glowing star', keywords: 'favorite shine' },
  { char: '💯', name: 'hundred points', keywords: '100 perfect' },
  { char: '💥', name: 'collision', keywords: 'boom explosion' },
  { char: '💡', name: 'light bulb', keywords: 'idea' },
  { char: '⚡', name: 'high voltage', keywords: 'lightning bolt energy' },
  { char: '🎉', name: 'party popper', keywords: 'celebrate confetti' },
  { char: '🎊', name: 'confetti ball', keywords: 'celebrate party' },
  { char: '🚀', name: 'rocket', keywords: 'launch fast ship' },
  { char: '🏆', name: 'trophy', keywords: 'win award' },
  { char: '🎯', name: 'direct hit', keywords: 'target goal' },
  { char: '✅', name: 'check mark button', keywords: 'done check yes complete' },
  { char: '☑️', name: 'check box with check', keywords: 'done check' },
  { char: '❌', name: 'cross mark', keywords: 'no wrong error' },
  { char: '⚠️', name: 'warning', keywords: 'caution alert' },
  { char: '❓', name: 'question mark', keywords: 'question' },
  { char: '❗', name: 'exclamation mark', keywords: 'important alert' },
  { char: '🚧', name: 'construction', keywords: 'wip in progress' },
  { char: '🔒', name: 'locked', keywords: 'lock private secure' },
  { char: '🔓', name: 'unlocked', keywords: 'unlock open' },
  { char: '🔑', name: 'key', keywords: 'key access' },
  { char: '🔗', name: 'link', keywords: 'chain url' },
  { char: '📌', name: 'pushpin', keywords: 'pin important' },
  { char: '📍', name: 'round pushpin', keywords: 'location pin' },
  { char: '📎', name: 'paperclip', keywords: 'attach' },
  { char: '📝', name: 'memo', keywords: 'note write' },
  { char: '📄', name: 'page facing up', keywords: 'file document' },
  { char: '📁', name: 'file folder', keywords: 'folder directory' },
  { char: '📅', name: 'calendar', keywords: 'date schedule' },
  { char: '⏰', name: 'alarm clock', keywords: 'time reminder' },
  { char: '⏳', name: 'hourglass not done', keywords: 'time waiting' },
  { char: '🗓️', name: 'spiral calendar', keywords: 'date schedule' },
  { char: '📈', name: 'chart increasing', keywords: 'growth stats up' },
  { char: '📉', name: 'chart decreasing', keywords: 'decline stats down' },
  { char: '📊', name: 'bar chart', keywords: 'stats data' },
  { char: '💰', name: 'money bag', keywords: 'money cash' },
  { char: '💸', name: 'money with wings', keywords: 'spend expensive' },
  { char: '💳', name: 'credit card', keywords: 'payment money' },
  { char: '📧', name: 'e-mail', keywords: 'email mail' },
  { char: '📞', name: 'telephone receiver', keywords: 'call phone' },
  { char: '💬', name: 'speech balloon', keywords: 'chat message comment' },
  { char: '💭', name: 'thought balloon', keywords: 'thinking idea' },
  { char: '🔍', name: 'magnifying glass tilted left', keywords: 'search find' },
  { char: '🛠️', name: 'hammer and wrench', keywords: 'tools build fix' },
  { char: '⚙️', name: 'gear', keywords: 'settings config' },
  { char: '🧩', name: 'puzzle piece', keywords: 'plugin integration' },
  { char: '🧠', name: 'brain', keywords: 'mind idea smart' },
  { char: '👀', name: 'eyes', keywords: 'look see watch' },
  { char: '🐛', name: 'bug', keywords: 'bug error issue' },
  { char: '💻', name: 'laptop', keywords: 'computer code' },
  { char: '🖥️', name: 'desktop computer', keywords: 'computer' },
  { char: '📱', name: 'mobile phone', keywords: 'phone mobile' },
  { char: '🖱️', name: 'computer mouse', keywords: 'mouse click' },
  { char: '☕', name: 'hot beverage', keywords: 'coffee tea' },
  { char: '🍕', name: 'pizza', keywords: 'food pizza' },
  { char: '🎵', name: 'musical note', keywords: 'music' },
  { char: '🎨', name: 'artist palette', keywords: 'design art' },
  { char: '🌍', name: 'globe showing europe-africa', keywords: 'world earth global' },
  { char: '🌈', name: 'rainbow', keywords: 'colorful pride' },
  { char: '☀️', name: 'sun', keywords: 'sunny weather' },
  { char: '🌙', name: 'crescent moon', keywords: 'night moon' },
  { char: '📦', name: 'package', keywords: 'box shipping' },
  { char: '🏠', name: 'house', keywords: 'home' },
  { char: '🚗', name: 'automobile', keywords: 'car' },
  { char: '✈️', name: 'airplane', keywords: 'travel flight' }
]
