/**
 * The MCP server, as a file on disk.
 *
 * Held as a string and written out at runtime rather than shipped as a second
 * bundle: in a packaged build the app's own code lives inside `app.asar`, and
 * whether a plain `node` process can load a module from in there is exactly
 * the kind of thing that works in development and fails silently once signed.
 * A file written to `userData` has no such question hanging over it, and it
 * can be opened and read when a run goes wrong.
 */

export const MCP_SHIM_SOURCE = `// Mindex MCP server — generated by Mindex. Do not edit; it is rewritten on
// every launch.
//
// A pipe, not an implementation. The search index lives in the Mindex app
// process, which is where it is kept current by the file watcher; this
// forwards each tool call to that process over a local socket and hands the
// answer back on stdio, which is the only transport an MCP client speaks.
//
// CommonJS on purpose. This is run by Electron's own binary in
// ELECTRON_RUN_AS_NODE mode when no separate Node is installed, and require()
// needs nothing arranged for it — no loader, no package type, no extension
// rule that a future Electron could tighten.
const net = require('node:net')

const SOCKET = process.env.MINDEX_MCP_SOCKET || ''
const TOKEN = process.env.MINDEX_MCP_TOKEN || ''
// Which conversation this server belongs to. Mindex mints it per conversation
// and looks up, on every call, what that conversation is currently allowed to
// reach — so narrowing the scope takes effect on the next message rather than
// needing the assistant restarted.
const SESSION = process.env.MINDEX_MCP_SESSION || ''
const CALL_TIMEOUT_MS = 15000

const TOOLS = [
  {
    name: 'search',
    description:
      'Full-text search across every note in the vault, ranked, with a snippet from each hit. Titles and tags are weighted above body text. Use this instead of Grep for "where did I write about X" — Grep sees literal strings in whatever files it walks, this sees the live index of the vault.',
    inputSchema: {
      type: 'object',
      properties: {
        query: { type: 'string', description: 'Words to search for.' },
        limit: { type: 'number', description: 'Maximum hits to return. Default 10, max 50.' }
      },
      required: ['query']
    }
  },
  {
    name: 'query',
    description:
      'Filter notes by their frontmatter fields. Use for "which notes ARE X" rather than "which notes MENTION X" — type:project status:ACTIVE, deadline:*, company:[[Acme]]. Terms are space-separated and combined with AND. Link fields match however the target note is written.',
    inputSchema: {
      type: 'object',
      properties: {
        filter: {
          type: 'string',
          description:
            'Filter expression. field:value equals; field:a,b any of; field:!=a none of; field:&a,b all of; field:~text contains; field:* has a value; field:!* has none; quotes protect spaces.'
        },
        limit: { type: 'number', description: 'Maximum notes to return. Default 50, max 200.' }
      },
      required: ['filter']
    }
  },
  {
    name: 'backlinks',
    description:
      'Every note that links to a given note. Accepts a vault-relative path or a note title, the same way a [[wikilink]] resolves.',
    inputSchema: {
      type: 'object',
      properties: {
        note: { type: 'string', description: 'Vault-relative path or note title.' }
      },
      required: ['note']
    }
  },
  {
    name: 'read',
    description:
      'The full text and frontmatter of one note — search and query only return a snippet. Accepts a vault-relative path or a note title, the same way a [[wikilink]] resolves.',
    inputSchema: {
      type: 'object',
      properties: {
        note: { type: 'string', description: 'Vault-relative path or note title.' }
      },
      required: ['note']
    }
  },
  {
    name: 'create',
    description:
      'Create a new note in the vault. Without a type, the note is plain markdown with no required frontmatter or sections.',
    inputSchema: {
      type: 'object',
      properties: {
        title: { type: 'string', description: 'The note\\'s title.' },
        folder: { type: 'string', description: 'Vault-relative folder. Default: the vault root, or the type\\'s own default folder.' },
        type: { type: 'string', description: 'A note type id already defined in this vault. Default: a plain untyped note.' },
        frontmatter: { type: 'object', description: 'Frontmatter fields to set.' },
        body: { type: 'string', description: 'Markdown body. Default: the type\\'s own starter template, or empty.' }
      },
      required: ['title']
    }
  },
  {
    name: 'answer',
    description:
      'Deliver your final answer for a task that asked for a specific shape. Call this exactly once, with the answer as the "result" object, and then stop. Do not also write the answer in your message.',
    inputSchema: {
      type: 'object',
      properties: {
        result: { type: 'object', description: 'The answer, in the shape the task asked for.' }
      },
      required: ['result']
    }
  },
  {
    name: 'update',
    description:
      'Replace the body (and optionally the frontmatter) of an existing note. Accepts a vault-relative path or a note title. This overwrites the whole body — read the note first if the change is not a full rewrite.',
    inputSchema: {
      type: 'object',
      properties: {
        note: { type: 'string', description: 'Vault-relative path or note title.' },
        body: { type: 'string', description: 'The new markdown body, in full.' },
        frontmatter: { type: 'object', description: 'Frontmatter fields to set. Omit to leave frontmatter unchanged.' }
      },
      required: ['note', 'body']
    }
  }
]

function write(message) {
  process.stdout.write(JSON.stringify(message) + '\\n')
}

function callBridge(method, params) {
  return new Promise((resolve, reject) => {
    if (!SOCKET) {
      reject(new Error('Mindex is not reachable: no socket was configured.'))
      return
    }
    const socket = net.connect(SOCKET)
    let buffer = ''
    let settled = false

    const timer = setTimeout(() => {
      if (settled) return
      settled = true
      socket.destroy()
      reject(new Error('Mindex did not answer in time.'))
    }, CALL_TIMEOUT_MS)

    function finish(err, data) {
      if (settled) return
      settled = true
      clearTimeout(timer)
      socket.end()
      if (err) reject(err)
      else resolve(data)
    }

    socket.setEncoding('utf8')
    socket.on('connect', () => {
      socket.write(JSON.stringify({ token: TOKEN, session: SESSION, method, params }) + '\\n')
    })
    socket.on('data', (chunk) => {
      buffer += chunk
      const nl = buffer.indexOf('\\n')
      if (nl === -1) return
      let response
      try {
        response = JSON.parse(buffer.slice(0, nl))
      } catch (err) {
        finish(err)
        return
      }
      if (response && response.ok) finish(null, response.data)
      else finish(new Error((response && response.error) || 'Mindex returned an error.'))
    })
    socket.on('error', (err) => finish(err))
    socket.on('close', () => {
      if (!settled) finish(new Error('Mindex closed the connection.'))
    })
  })
}

async function handle(message) {
  const id = message.id
  const method = message.method

  if (method === 'initialize') {
    const asked = message.params && message.params.protocolVersion
    write({
      jsonrpc: '2.0',
      id,
      result: {
        // Echo the client's own version rather than naming one: this server
        // has no version-specific behaviour to gate, and guessing a string
        // wrong is a handshake failure with no useful error.
        protocolVersion: typeof asked === 'string' ? asked : '2025-06-18',
        capabilities: { tools: {} },
        serverInfo: { name: 'mindex', version: '1.0.0' }
      }
    })
    return
  }

  if (method === 'notifications/initialized' || method === 'notifications/cancelled') return

  if (method === 'tools/list') {
    write({ jsonrpc: '2.0', id, result: { tools: TOOLS } })
    return
  }

  if (method === 'tools/call') {
    const params = message.params || {}
    const name = params.name
    const args = params.arguments || {}
    if (!TOOLS.some((t) => t.name === name)) {
      write({ jsonrpc: '2.0', id, error: { code: -32601, message: 'Unknown tool: ' + name } })
      return
    }
    try {
      const data = await callBridge(name, args)
      write({
        jsonrpc: '2.0',
        id,
        result: { content: [{ type: 'text', text: JSON.stringify(data, null, 2) }] }
      })
    } catch (err) {
      // Reported as a tool result, not a protocol error: the model can read
      // this and try something else, whereas a JSON-RPC error aborts the call
      // with nothing it can act on.
      write({
        jsonrpc: '2.0',
        id,
        result: {
          isError: true,
          content: [{ type: 'text', text: String((err && err.message) || err) }]
        }
      })
    }
    return
  }

  if (id !== undefined && id !== null) {
    write({ jsonrpc: '2.0', id, error: { code: -32601, message: 'Method not found: ' + method } })
  }
}

let stdinBuffer = ''
process.stdin.setEncoding('utf8')
process.stdin.on('data', (chunk) => {
  stdinBuffer += chunk
  for (;;) {
    const nl = stdinBuffer.indexOf('\\n')
    if (nl === -1) break
    const line = stdinBuffer.slice(0, nl).trim()
    stdinBuffer = stdinBuffer.slice(nl + 1)
    if (!line) continue
    let message
    try {
      message = JSON.parse(line)
    } catch {
      continue
    }
    Promise.resolve(handle(message)).catch((err) => {
      process.stderr.write('[mindex-mcp] ' + String((err && err.message) || err) + '\\n')
    })
  }
})
process.stdin.on('end', () => process.exit(0))
`
